Update readme.md
Obsidian-TTRPG-Community/ObsidianTTRPGShare pull request #120
Opened 2023-05-25 13:39 UTC by ObsidianTTRPGProject

Added new css style for Level formatting.

2023-05-25 15:12 UTC, mProjectsCode commented
Maybe consider moving the images to a new line. This is how it looks on GitHub currently.
![image](https://github.com/Obsidian-TTRPG-Community/ObsidianTTRPGShare/assets/61602848/5202e992-70de-4dd3-a8fb-933e167a08c4)

2023-05-25 16:58 UTC, sigrunixia requested changes

2023-05-25 16:58 UTC, sigrunixia commented on Pathfinder/2E/action-icons/readme.md
> +### Action Icons
Add a line Break before and after each header

```
## Installation

### Action Icons
```

2023-05-25 16:58 UTC, sigrunixia commented on Pathfinder/2E/action-icons/readme.md
>  *⭓{ .Pathfinder }* - Free Action
De-facto list items, so line break :)


```
*⭓{ .Pathfinder }* - Free Action

*⬲{ .Pathfinder }* - Reaction
```

2023-05-25 16:58 UTC, sigrunixia commented on Pathfinder/2E/action-icons/readme.md
> +1. Copy the \*.md from the Templates folder into your Vaults template folder.
Enforcement of space between Header and List Items

```
### Level Text Highlighter

 1. Copy the \*.md from the Templates folder into your Vaults template folder. 
```

2023-05-25 16:58 UTC, sigrunixia commented on Pathfinder/2E/action-icons/readme.md
> +![image](https://github.com/Obsidian-TTRPG-Community/ObsidianTTRPGShare/assets/96321415/a2a60edf-4c32-4d9d-b836-7cb8310fee40)
Github sees this as One Line.

```
Text{.hltr-level}

 **Example** 

 ![image](https://github.com/Obsidian-TTRPG-Community/ObsidianTTRPGShare/assets/96321415/a2a60edf-4c32-4d9d-b836-7cb8310fee40)
```

2023-05-25 16:58 UTC, sigrunixia commented on Pathfinder/2E/action-icons/readme.md
> +![image](https://github.com/Obsidian-TTRPG-Community/ObsidianTTRPGShare/assets/96321415/6f4d5183-8592-4f5f-9372-2adc065657a0)
Similarly here, this is viewed as One line. Headers might also be appropriate here. Whichever ends up looking better.


```
**Examples**

 ![image](https://github.com/Obsidian-TTRPG-Community/ObsidianTTRPGShare/assets/96321415/6f4d5183-8592-4f5f-9372-2adc065657a0)
```

2023-05-25 17:01 UTC, sigrunixia commented
Adding this here as well, if you use VSCode to check the work before adding it to Github, there is a lovely [plugin which shows a Github Preview](https://marketplace.visualstudio.com/items?itemName=bierner.github-markdown-preview). It _might_ also now be included in Github for VScode, but I do not use it anymore. 

Intellijidea and has it built in.

2023-05-30 17:26 UTC, sigrunixia approved these changes

2023-05-30 17:26 UTC, sigrunixia commented on Pathfinder/2E/action-icons/readme.md
>  *⭓{ .Pathfinder }* - Free Action
Resolved with my update

2023-05-30 17:32 UTC, merged